# Generated by Django 5.0.7 on 2024-10-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_nationalimplementationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='places',
            field=models.ManyToManyField(related_name='campaigns', to='campaign.place'),
        ),
    ]
