# Generated by Django 5.0.7 on 2024-10-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicarea',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematic_areas', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='thematicarea',
            name='level',
            field=models.CharField(choices=[('national', 'National'), ('regional', 'Regional')], max_length=50),
        ),
    ]
