# Generated by Django 5.0.7 on 2024-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_thematicarea_campaign_alter_thematicarea_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='Uganda', max_length=255),
            preserve_default=False,
        ),
    ]
