# Generated by Django 5.0.7 on 2024-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicarea',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
