# Generated by Django 5.0.7 on 2024-11-08 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_user_place_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.IntegerField()),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.activity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.place')),
            ],
        ),
    ]
